stages:
  parse_corpus:
    cmd: python src/parse_corpus.py
    deps:
    - data/raw
    - data/raw/metadata.csv
    - src/parse_corpus.py
    outs:
    - data/processed/phoneme_table.csv
  extract_acoustics:
    cmd: pixi run python src/extract_acoustics.py
    deps:
    - data/processed/phoneme_table.csv
    - data/raw
    - src/extract_acoustics.py
    outs:
    - data/features/features_acoustic.csv
